### ISSUE TITLE
TEI for Book Section

### ISSUE THREAD

**Issue by wsalesky** [srophe/caesarea-data#11]
@davidamichelson @wlpotter What should the TEI look like for  a Book Section a record imported from Zotero? We do not seem to have coded for this, and the import is currently just dropping the book title. I can easily add it, just want to make sure I format the biblStruct correctly. 

Example record: 
http://wwwb.library.vanderbilt.edu/exist/apps/caesarea/bibl/S935RWI7

TEI:
```
<biblStruct>
<analytic>
<editor>
<forename>John H.</forename>
<surname>Humphrey</surname>
</editor>
<author>
<forename>Kenneth G.</forename>
<surname>Holum</surname>
</author>
<title level="a">
Inscriptions from the Imperial Revenue Office of Byzantine Caesarea Palaestinae
</title>
<idno type="URI">https://caesarea-maritima.org/bibl/S935RWI7</idno>
<idno type="URI">
https://www.zotero.org/groups/caesarea-maritima/items/S935RWI7
</idno>
<idno type="URI">
https://www.zotero.org/groups/2320447/items/S935RWI7
</idno>
<idno type="URI">
http://www.worldcat.org/oclc/1070421280 Abbreviation: RBNE
</idno>
</analytic>
<monogr>
<title>Journal of Roman Archaeology Supplement</title>
<textLang mainLang="en"/>
<imprint>
<pubPlace>Ann Arbor, MI</pubPlace>
<publisher>Journal of Roman Archaeology</publisher>
<date>1995</date>
</imprint>
<biblScope unit="pp">333-345</biblScope>
</monogr>
</biblStruct>

```
Zotero record: 
https://www.zotero.org/groups/2320447/caesarea-maritima/items/S935RWI7?

**Comment by wlpotter** [comment]
@wsalesky here are the changes we would make (note, I am referencing [this CSL JSON file](https://gist.github.com/wlpotter/6ef9372b0f6f079be21d565cafb3effd) which I exported from Zotero's desktop client. I am hoping it is the same used by the import): 

- the `monogr/title` should have an `@level="m"` attribute.
- the text node for `monogr/title` should derive from the "container-title" property value, in this case "The Roman and Byzantine Near East: Some Recent Archaeological Research". (I think currently it is coming from the "collection-title" property value?)
- for book sections (which the JSON seems to type as "chapter"), we would want any information for the "editor" property to be included in the `biblStruct/monogr` element -- rather than the `analytic` level. 
-  series information, when applicable, should appear in a `biblStruct/series`. The "collection-title" value, "Journal of Roman Archaeology Supplement" should be the textnode of the `biblStruct/series/title[@level="s"]`. The "collection-number" value, "14", should be the textnode of the `biblStruct/series/biblScope`. Note that this would be true of "monograph" records as well, if they have associated series info. (here is an example of such a record: http://wwwb.library.vanderbilt.edu/exist/apps/caesarea/bibl/9DIE2FPH)


Below is an updated example of the biblStruct for https://www.zotero.org/groups/2320447/caesarea-maritima/items/S935RWI7?

```
<biblStruct>
<analytic>
<author>
<forename>Kenneth G.</forename>
<surname>Holum</surname>
</author>
<title level="a">
Inscriptions from the Imperial Revenue Office of Byzantine Caesarea Palaestinae
</title>
<idno type="URI">https://caesarea-maritima.org/bibl/S935RWI7</idno>
<idno type="URI">
https://www.zotero.org/groups/caesarea-maritima/items/S935RWI7
</idno>
<idno type="URI">
https://www.zotero.org/groups/2320447/items/S935RWI7
</idno>
<idno type="URI">
http://www.worldcat.org/oclc/1070421280 Abbreviation: RBNE
</idno>
</analytic>
<monogr>
<title level="m">The Roman and Byzantine Near East: Some Recent Archaeological Research</title>
<editor>
<forename>John H.</forename>
<surname>Humphrey</surname>
</editor>
<textLang mainLang="en"/>
<imprint>
<pubPlace>Ann Arbor, MI</pubPlace>
<publisher>Journal of Roman Archaeology</publisher>
<date>1995</date>
</imprint>
<biblScope unit="pp">333-345</biblScope>
</monogr>
<series>
<title level="s">Journal of Roman Archaeology Supplement</title>
<biblScope>14</biblScope>
</series>
</biblStruct>
```

There is an issue with the OCLC number as well, but that's my fault for not communicating how we were encoding Zotero's "Extra" field. I will make a separate issue for that...

Let me know if any of this is unclear. And @davidamichelson let me know if I missed anything.

**Comment by wlpotter** [comment]
@wsalesky I believe this is ready to go. Let me know if the above example and notes are unclear.

**Comment by wsalesky** [comment]
@wlpotter fixed. Please take a look and if it is correct you can close this issue. 
Thanks.

**Comment by wsalesky** [comment]
@wlpotter do you mean in the HTML display? (also link to example record?)

**Comment by wlpotter** [comment]
@wsalesky Yes, sorry, in the HTML display. Example: http://wwwb.library.vanderbilt.edu/exist/apps/caesarea/bibl/S935RWI7

**Comment by wsalesky** [comment]
@wlpotter Okay, that is a simple fix. Does the underlying TEI look right?

**Comment by wlpotter** [comment]
Yes, it does.

**Comment by wlpotter** [comment]
@wsalesky Okay, so one small change to the TEI. 

Could we have, for book section records, the OCLC information (which is in the "Extra field" and identified as "OCLC: \d+") output at the monograph level.

The xpath will be: `tei:biblStruct/monogr/idno[@type="URI"]`. This idno should come directly before the tei:textLang element.

here is an example (from [this record](http://wwwb.library.vanderbilt.edu/exist/apps/caesarea/bibl/S935RWI7)) of the resulting element:
```
<monogr>
    <title level="m">The Roman and Byzantine Near East: Some Recent Archaeological Research</title>
    <editor>
        <forename>John H.</forename>
        <surname>Humphrey</surname>
    </editor>
    <idno type="URI">http://www.worldcat.org/oclc/1070421280</idno>
    <textLang mainLang="en"/>
...
</monogr>
```
