### ISSUE TITLE
Missing bibls?

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea-data#137]
@wlpotter This record: [https://caesarea-maritima.org/testimonia/214](https://caesarea-maritima.org/testimonia/214.tei) has 
```<ab type="translation" xml:lang="en" xml:id="quote214-2" source="#bib214-2">```

But in the listBibl there is no bib214-2

This appears to be one where Joe translated the English himself, is this a one off mistaken record or is this an artifact from a script that adds in bibls?

**Comment by wlpotter** [comment]
Hmm I think this is from the post-processor. I'll update it so that it checks to see if there is a bibl for the translation. 
I'll also see how widespread this problem is to see if it's worth running an update script to remove the sources.

Note to self:

- test whether `//body/listBibl[1]/bibl[2]` is non-empty and only add the `@source` attribute if it is non-empty.
