### ISSUE TITLE
Date of publication at repeating bottom of page should be updated from 2021 to 2022

### ISSUE THREAD

**Issue by josephrife** [srophe/caesarea-data#161]
Any way to fix this so that it automatically updates with each new year?

**Comment by davidamichelson** [comment]
Batch update: Except for materials quoted from other sources, this entry is copyright 2021 by the contributors (Joseph L. Rife, et al.) and the Caesarea City and Port Exploration Project. It is licensed under the Attribution 4.0 International (CC BY 4.0) license.

**Comment by wlpotter** [comment]
FYI @davidamichelson I'm assigning myself as this can be done in a batch change to the `//availability/license` text. I also noticed a few of the more recent records, e.g. https://caesarea-maritima.org/testimonia/395.tei were missing this text. I think this might be an issue of which version of the data template was used to create those, but I need to look further into it.

**Comment by wlpotter** [comment]
FYI I've updated all data to "this entry is copyright 2023". We may want to discuss mechanisms for updating this automatically? Though wouldn't the date of initial publication be the copyrighted date?

**Comment by wlpotter** [comment]
To do here:

- make an app issue to update the how to cite prose to read "entry published" rather than "last modified"
- add to the license text the year from fn:current-date whenever the post-processing or ingest-edits scripts run (and make sure it updates the publication date too...)
  - this should also be run on current data to update it so that the publication date and copyright date match

**Comment by wlpotter** [comment]
Fixed in current data; new records will have the current year added to the copyright date any time the processing script is run
