### ISSUE TITLE
Create drop down based on types of translator based on the prolegomena docuemtnb

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea-data#163]

**Comment by wlpotter** [comment]
Pulling these in here as notes for myself:

- Translation of text-passage retyped verbatim from a published source, cited by author-date.
  - Text node: "Trans. "
  - Label: "Trans. {source}"
  - Hint:  "Translation of text-passage retyped verbatim from a published source, cited by author-date."
- Minor adjustments for clarity from a published source
  - Text node: "Revised from "
  - Label: "Revised from {source}"
  - Hint: "Editor has essentially used the words of a published source, as cited by author-date, but has made minor adjustments for clarity or the purposes of caesarea-maritima.org, such as form or spelling of names of places or persons, touching up diction, adjusting punctuation."
- Significant rewrite of a published source
  - Text node: "Adapted from "
  - Label: "Adapted from {source}"
  - Hint: "Editor has rewritten in significant ways the words of a published source, as cited by author-date, in the interests of strict accuracy and readability."
- Published source unacceptable translation, but editor's translation sufficiently benefited from knowledge of source 
  - Text node: "Trans.  with reference to "
  - Label: "Trans. {editor name} with reference to {source(s)}"
  - Hint: "Editor has translated text-passage because published sources, cited by author-date, are unacceptable on grounds of strict accuracy and/or readability. However, Editor considers his/her translation to have sufficiently benefited from knowledge of (an)other published translation(s) as to merit explicit reference to those sources."
- Editor gives new translation and claims full ownership
  - Text node: "Trans. "
  - Label: "Trans. {editor name}"
  - Hint: "Editor gives new translation over which they claim full ownership. Either (most often) no published translation of text-passage exists, or (very rarely) published translations have been deemed undeserving of reference or citation."

**Comment by wlpotter** [comment]
I suppose another way to do it would be to label the cited reference (i.e., the tei:bibl) for the translation in the form, and then the processor could parse that into a text node? So the bibls would have the following drop-down:

- "Trans. source"
- "Revised from"
- "Adapted from"
- Trans. with reference to"

Then the translation note would have a drop down for the editor id of the person doing the translation, and the processor could put the two together based on the two drop-down selections.

**Comment by wlpotter** [comment]
Note to self: I went with the option of a dropdown (i.e., `oxy_combobox`) for each of the cases. Also, since the combo box needed to be editable, I couldn't have separate values and labels. This turned out fine since it is clearer to have the "Trans. {source}", and replace what's in curly braces than just "Trans. ".
