### ISSUE TITLE
Mark the origDate with @period

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea-data#3]
https://github.com/srophe/caesarea/issues/6

**Comment by wlpotter** [comment]
@davidamichelson I've added period attributes. However, there are some overlaps in the taxonomy. An example would be from Josephus: https://github.com/srophe/caesarea-data/blob/master/data/testimonia/tei/4.xml#L228

As you can see from the example, I've added the different periods as space-separated pointers. We should decide if we want to allow multiple periods or not - likely a conversation with the editors. If we do go that direction, this is not something a script will be able to sort out anymore.

I'm leaving this open until we've discussed if having multiple period values is alright.

**Comment by wlpotter** [comment]
Multiple, space-separated period values is fine. Closing this issue.

**Comment by wlpotter** [comment]
@davidamichelson  I'm reopening this because I noticed that the `@period` attribute with multiple, space-separated values is not validating. The attribute requires a teidata.pointer value, meaning it must refer to a single URI (can be relative or absolute, so something like "#earlyRoman" is valid but "#earlyRoman #nabataen" is not. 

Is this cause for us to change our practices? I understand why the teidata.pointer data type is so restrictive, but I don't agree with the application of it to the `@period` attribute as there are many cases when a date or date range would fall within multiple periods - as in our case, for example. We will need to discuss this.

**Comment by davidamichelson** [comment]
Yes, let's bring Dan in on this. Maybe a change request to TEI

**Comment by wlpotter** [comment]
Notes for TEI list:

# Allow @period to have Datatype of "1–∞ occurrences of [teidata.pointer](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-teidata.pointer.html) separated by whitespace"

Currently, the datatype of the `@period` attribute allows only a single value of type teidata.pointer. This proposal requests that the `@period` attribute's datatype be changed to allow "1–∞ occurrences of [teidata.pointer](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-teidata.pointer.html) separated by whitespace". There are many cases where a datable event occurs within or across the boundaries of multiple named-periods. The `@period` attribute, as it stands, cannot accurately nor precisely capture such cases.

As an example, take the following case from a Classics project I am currently working on. We would like, in this project, to capture both the composition date (or date range) of a given work, and the named chronological period(s) that correspond to that composition date. We are using the chronology from [The New Encyclopedia of Archaeological Excavations in the Holy Land](http://n2t.net/ark:/99152/p0dkm29), which we reference in a `/TEI/teiHeader/encodingDesc/classDecl/taxonomy`. Due to differences based on geographical sub-regions and other issues in historical periodization, has several overlapping periods. So, if we were to specify the composition date of Joesphus' _Antiquities of the Jews_ using a tei:origDate, we would like to have `<origDate period="#nabateanKingdom #earlyRoman" notBefore="0093" notAfter="0094">93 - 94 CE</origDate>`. The multiple attribute vales on `@period`, however, will not validate with the current TEI schema.

**Comment by wlpotter** [comment]
Here is an example record: https://github.com/srophe/caesarea-data/blob/master/data/testimonia/tei/10.xml#L238

**Comment by wlpotter** [comment]
Link to feature request: https://github.com/TEIC/TEI/issues/2002

**Comment by davidamichelson** [comment]
Good feedback from TEI council above.

I would suggest we propose this definition (which draws on language in the definition of @ref in [att.canonical](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-att.canonical.html)

"supplies one or more pointers to some location defining a named period of time within which the datable item is understood to have occurred. If more than one pointer is supplied the implication is that the datable item occurred, at least in part, within all of the time periods identified. Ambiguous identifications (such as uncertainty, gaps, or overlaps in the chronological data) can be clarified by the TEI:precision element."

Examples for the @precision scenarios would be:

Basic example:
Data: Josephus' _Antiquities of the Jews_ was written in 93 - 94 CE which is part of two different periodizations (the period of the Nabatean Kingdom, 168 BCE-106 CE and the Early Roman period, 37 BCE-132 CE)

Encoding:
```
<origDate period="#nabateanKingdom #earlyRoman" notBefore="0093" notAfter="0094">93 - 94 CE</origDate>
```
Uncertain Overlap Example:
Data: Josephus' _Lost Undated Sequel_ was written at an unidentified date between 100 - 110 CE which is potentially part of one or two different periodizations (the period of the Nabatean Kingdom, 168 BCE-106 CE and the Early Roman period, 37 BCE-132 CE). In most cases, it might not be necessary to annotate this ambiguity since the overlap is clear in the @notBefore and @notAfter values, but it could be expressed as follows if desired:

```
<origDate period="#nabateanKingdom #earlyRoman" notBefore="0100" notAfter="0110">93 - 94 CE
<precision match="@period" precision="low"><desc>This lost work may have been written either during the last years of the Nabatean Kingdom Period or in the portion of the Early Roman Period after the end of the Nabatean Kingdom Period.
</desc>
</precision>
</origDate>
```

Uncertain Non-Overlap Example:
Data: Josephus' _Postmortem Biography_ was written at an unidentified date between 130-140 CE which is exclusively part of one of two different periodizations (the Early Roman period, 37 BCE-132 CE or the Late Roman Period, 132 CE-324 CE). In most cases, it might not be necessary to annotate this ambiguity since the numeric correspondence is clear in the @notBefore and @notAfter values, but it could be expressed as follows if desired:

```
<origDate period="#earlyRoman #lateRoman" notBefore="0130" notAfter="0140">130-140 CE
<precision match="@period" precision="low"><desc>This lost work was written either in the Early Roman Period or the Late Roman Period.
</desc>
</precision>
</origDate>
```

**Comment by davidamichelson** [comment]
@wlpotter Did this ever get acted on by the council?

**Comment by davidamichelson** [comment]
- [ ] We should note this as an innovation in the TEI in the documentation.

**Comment by wlpotter** [comment]
@davidamichelson It did, see https://github.com/TEIC/TEI/issues/2002#issuecomment-716172012

If TEI documentation updates, do we need to include in our documentation?

**Comment by davidamichelson** [comment]
Great, we want to make a note in our documentation that this was a change we requested.

**Comment by wlpotter** [comment]
Added to the documentation
