### ISSUE TITLE
We need help with these obscure testimonia.

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea-data#34]
There are 77 partial records which need further editorial intervention.

**Comment by wlpotter** [comment]
In addition to the ones marked on the [testimonia data entry sheet](https://docs.google.com/spreadsheets/d/1ZG8blfcVZ62zSkkW22HEbUyMYm7gaqP4wmzcts4AA1A/edit#gid=0), the following testimonia have proven difficult to find:

- [ ] P.Zenon, Sammelbuch III.1.6777 (trouble finding this source).
- [ ] Artemidorus of Ephesus apud Marcianus of Heracleia, GGM 576 (ref is a page number rather than a section of the work)
- [ ] Papiri Greci e Latini-Publicazioni della Società Italiana, 9.36f, 1026 (ref is a compilation of papyri, not a specific work)
- [ ] Jerome, xxx q.v. II.A (Levine Roman Caesarea p. 17 n. 105) (work not specified; need to look up reference)
- [ ] Julian of Ascalon, xxx (Levine Roman Caesarea p. 9 n. 35) (work not specified; need to look up reference)
- [ ] Itinerarium Burdigalense, CCSL 175, p. 13 (ref is a page number rather than a section of the work)
- [ ] Peregrinatio Sanctae Paulae, Itinera et Descriptiones Terrae Sancta (ed. T. Tobler, Geneva 1877) I, p. 31 (ref is a page number rather than a section of the work)
- [ ] Le Bas and Waddington III.1620* (ref is to an edition/compilation of works. Need to look at to find specific work)
- [ ] Origen passim (need more specifics...)
- [ ] Nicetas the Paphlagonian (ed. Halkin 1962) (need more specifics...)
- [ ] Severus of Antioch, epp. xxx  (need more specifics...) **Note**: I looked at SPEAR to see if there were any references to Caesarea Maritima noted in the letters of Severus, but the only references to Caesarea were to Philippi.
- [ ] Vita s. Melaniae Iunioris xxx  (need more specifics...)
- [ ] Cyril of Scythopolis, Vita s. Sabas pp. 162, 171-172 (ed. Schwartz 1939) (ref is to page numbers rather than section of the work)

Some of these just need the work to be tracked down by page number, which may not require Joe's assistance, but others will certainly need further research by him.

**Comment by davidamichelson** [comment]
I will take the others from the testimonia sheet

**Comment by davidamichelson** [comment]
We need to consolidate this.

**Comment by wlpotter** [comment]
I am consolidating these here for review: https://docs.google.com/spreadsheets/d/1ZG8blfcVZ62zSkkW22HEbUyMYm7gaqP4wmzcts4AA1A/edit#gid=1754620617
