### ISSUE TITLE
Eusebius of Caesarea has two names

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea-data#53]
https://caesarea-maritima.org/testimonia/browse.html?facet-authorTestimonia=Eusebius 

https://caesarea-maritima.org/testimonia/browse.html?facet-authorTestimonia=Eusebius%20of%20Caesarea

https://caesarea-maritima.org/testimonia/101

https://caesarea-maritima.org/testimonia/browse.html?facet-authorTestimonia=Eusebius&

**Comment by wsalesky** [comment]
@davidamichelson They use the same viaf ref. So there is only one showing up on the facets. The real problem is how to pass the correct value to the XSLT for the look up in records that use : Eusebius of Caesarea

I was being lazy and just passing the text label, may need to rethink how that function works.

**Comment by davidamichelson** [comment]
@wsalesky Thanks we plan to just make them have the same name. The different strings is causing a problem for facets here: https://caesarea-maritima.org/testimonia/browse.html?facet-authorTestimonia=Eusebius%20of%20Caesarea (no results when there shoudl be some)

**Comment by davidamichelson** [comment]
Don't fix the facets, we will fix the data.

**Comment by wlpotter** [comment]
Fixed
