### ISSUE TITLE
Luke. Acts 9.30. has period at the end of the title

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea-data#7]
Is this a typo? http://wwwb.library.vanderbilt.edu/exist/apps/caesarea/testimonia/66

**Comment by davidamichelson** [comment]
Also, I think we should change the name to Luke the Evangelist (in general it is useful to add epithets. We may want to add this not to our manual)

**Comment by wlpotter** [comment]
@davidamichelson ah, yes. This came from the spreadsheet. Since the cited ranges were listed as numbers, we included a period for the ones that ended in 0 so the spreadsheet didn't strip out the zeroes as "unnecessary". I will go back through and update these.

And I can make the change to Luke the Evangelist in the data and add the note to the manual.

**Comment by wlpotter** [comment]
Both of these should be fixed.
