### ISSUE TITLE
data entry

### ISSUE THREAD

**Issue by josephrife** [srophe/caesarea-data#79]
Will could you add the earlier periods (Iron Age etc) to the bulleted list of possible periods in the date-entry form for testimonia?

**Comment by wlpotter** [comment]
@josephrife sure thing! I will add those this afternoon. FYI, this shouldn't affect the template as the input values are controlled separately, so you won't need to re-download the template.

**Comment by wlpotter** [comment]
@josephrife The form should now have all the periods from the taxonomy (you may have to switch to 'text' view and then back to 'author' view to refresh it). Let me know if this looks good.

**Comment by josephrife** [comment]
Thanks Will. Oh no, what do I do about the forms I filled out this morning? many thanks  Joe
Something else. Could you add a third data-entry box, above the other two, on the form below the "excerpt from edition" box?
Then it would go:
- Textual note (the new box)
- Discussion note (already there)
- Corrigenda note (already there)
many thanks,  Joe
-----------------------------------------------------------------
Joseph L. Rife
Associate Professor
Department of Classical and Mediterranean Studies
Affiliated Faculty in Anthropology and Religion
Director, The American Excavations at Kenchreai (Greece)
Co-Director, The Caesarea City and Port Exploration Project (Israel)


________________________________

**Comment by wlpotter** [comment]
@josephrife Adding the extra check boxes shouldn't have adversely affected the forms filled out before the change, and they should have the new check boxes (but do let me know if this is not the case).

I will add in the textual note today. Since that change requires an update to the underlying form, I will include instructions to re-download the new form as well as how to update the forms you've already filled out with a textual note. Should have this ready for you later this morning.

**Comment by wlpotter** [comment]
These two updates have been implemented; I will close this issue and other template/form requests can be opened as new issues.
